### ISSUE TITLE
Add some description along with app name?

### ISSUE THREAD

**Issue by niksmac** [learn-anything/macos-apps#3]
Consider adding some description along with app name so that people know what is the app exactly about.

**Comment by HZooly** [comment]
I take advantage of your remark to ask a related question:

Why all list items are not capitalized? I know you already did like this in some of your repository (Youtube in example).

**Comment by nikivdev** [comment]
@niksmac I will add the descriptions to the apps, you are right. If you want to help with this, you can do it. 🙂 

@TorzuoliH We will be capitalising and making the curated a lot better very soon. They will be similar in quality to [Alfred Workflows list](https://github.com/learn-anything/alfred-workflows).

**Comment by HZooly** [comment]
@nikitavoloboev I was exactly thinking about this list!

**Comment by niksmac** [comment]
@nikitavoloboev sure, ill chip in sometime soon.

**Comment by nikivdev** [comment]
I am going to close this but you are welcome to add descriptions to the apps.
